# Generated by Django 2.2.5 on 2019-09-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sctest', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSorce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('math', models.FloatField()),
                ('english', models.FloatField()),
                ('chiness', models.FloatField()),
            ],
        ),
    ]
